# coding: utf-8

"""
    设备开放API

    worth open api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import worth
from worth.api.authenticator_api import AuthenticatorApi  # noqa: E501
from worth.rest import ApiException


class TestAuthenticatorApi(unittest.TestCase):
    """AuthenticatorApi unit test stubs"""

    def setUp(self):
        self.api = worth.api.authenticator_api.AuthenticatorApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_gen_token(self):
        """Test case for gen_token

        生成token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
