# coding: utf-8

"""
    设备开放API

    worth open api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import worth
from worth.api.device_api import DeviceApi  # noqa: E501
from worth.rest import ApiException


class TestDeviceApi(unittest.TestCase):
    """DeviceApi unit test stubs"""

    def setUp(self):
        self.api = worth.api.device_api.DeviceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_send_action(self):
        """Test case for send_action

        发送指令  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
