# coding: utf-8

"""
    设备开放API

    worth open api  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import worth
from worth.models.action_req import ActionReq  # noqa: E501
from worth.rest import ApiException

class TestActionReq(unittest.TestCase):
    """ActionReq unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ActionReq
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = worth.models.action_req.ActionReq()  # noqa: E501
        if include_optional :
            return ActionReq(
                device_id = '0', 
                data = '0', 
                charset = '0'
            )
        else :
            return ActionReq(
                device_id = '0',
                data = '0',
        )

    def testActionReq(self):
        """Test ActionReq"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
